/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData folder_open = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_a_photo = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_circle = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_box = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_balance = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_to_photos = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assignment = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assessment = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backup = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_color = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_arrow_left = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vertical_align_bottom = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vertical_align_top = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_1 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_text_inv_1 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_line = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_area = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_1 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_1 = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_2 = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_1 = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assignment_ind = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assignment_turned_in = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData content_paste = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_3 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint_1 = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData open_in_browser = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payment = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power_settings_new = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_hand = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_hand = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData off = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_1 = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_1 = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_2 = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_2 = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_outline = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_3 = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_3 = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData enter_down = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit_up = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_balance_wallet = IconData(0xf008, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xf044, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open_1 = IconData(0xf068, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_empty = IconData(0xf069, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xf07b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_square = IconData(0xf082, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled_alt = IconData(0xf086, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xf08c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_plus_g = IconData(0xf0d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_text = IconData(0xf0f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_arrow = IconData(0xf124, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_square = IconData(0xf14d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar_sign = IconData(0xf155, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rupee = IconData(0xf156, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_text_inv = IconData(0xf15c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xf16d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = IconData(0xf175, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xf176, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xf1f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData whatsapp = IconData(0xf232, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_plus = IconData(0xf234, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sticky_note_o = IconData(0xf24a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData percent = IconData(0xf295, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address_card = IconData(0xf2bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xf303, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xf3bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply = IconData(0xf3e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_alt = IconData(0xf406, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_open_empty = IconData(0xf4c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_invoice = IconData(0xf570, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_invoice_dollar = IconData(0xf571, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_signature = IconData(0xf573, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint = IconData(0xf577, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
